### ISSUE TITLE
px-dropdown display-value resets to "Select" when in checkbox mode

### ISSUE THREAD

**Issue by j12y** [PredixDev/px-dropdown#47] opened 2017-06-02 20:44 UTC
## Expected behavior and actual behavior:

I set the `display-value` to "Select Sensor(s)" and it was rendered as such, but as soon as a checkbox is selected it reverts displayValue to default of "Select".  I would have expected it to remain with the same label I chose and set as the `display-value`.

## Steps to reproduce the problem:

From bower.json:
    "px-dropdown": "^3.1.1",

```
        <px-dropdown display-value="Select Sensor(s)" checkbox-mode="true">
            <px-dropdown-content checkbox-mode='true' extend-dropdown='true' extend-dropdown-by='25'
                    max-cont-character-width='10'
                    items='{{ sensors }}'>
            </px-dropdown-content>
        </px-dropdown>
```

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):

Chrome.

**Comment by randyaskin** [comment] 2017-06-05 16:10
Duplicate of #40 though this title is clearer.

**Closed by randyaskin** 2017-06-05 16:10 UTC
